import type { Language, UILabels } from './types';

const LABELS: Record<Language, UILabels> = {
  english: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'Understanding your medicines, made simple.',
    dropzone: 'Drop your prescription here\nor click to choose a file',
    dropzoneHint: 'Accepted: PDF, JPG, PNG  •  Max size: 20MB',
    processButton: '📤  Process My Document',
    connectCalendar: '📅 Connect Google Calendar (optional)',
    calendarConnected: '✅ Google Calendar Connected',
    processingMsg1: 'Reading your document...',
    processingMsg2: 'Understanding your medicines...',
    processingMsg3: 'Getting everything ready for you...',
    processingWait: 'Please wait. This may take a minute.',
    listenButton: '🔊 Listen to this',
    readButton: '📖 Read as text',
    pauseButton: '⏸ Pause',
    stopButton: '⏹ Stop',
    resumeButton: '▶️ Resume',
    askPlaceholder: 'Ask me anything about your medicines...',
    sendButton: 'Send →',
    addReminders: '📅 Add Medicine Reminders',
    newDocument: '📤 New Document',
    greetingPrefix: "🤝 Hi! I've read your document. Here is what your doctor said 👇",
    generatingAudio: '🎵 Generating audio... (first time may take a moment)',
    audioGenerationComplete: '✅ Audio generation complete',
    playAudioButton: '▶️ Play Audio',
    replayAudioButton: '🔄 Replay from Start',
    downloadAudioButton: '💾 Save this in my system',
    audioDownloaded: '✅ Downloaded',
  },
  hindi: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'अपनी दवाइयों को आसानी से समझें।',
    dropzone: 'यहाँ अपना नुस्खा डालें\nया फ़ाइल चुनने के लिए क्लिक करें',
    dropzoneHint: 'स्वीकृत: PDF, JPG, PNG  •  अधिकतम आकार: 20MB',
    processButton: '📤  मेरा दस्तावेज़ प्रोसेस करें',
    connectCalendar: '📅 Google Calendar जोड़ें (वैकल्पिक)',
    calendarConnected: '✅ Google Calendar जुड़ा हुआ है',
    processingMsg1: 'आपका दस्तावेज़ पढ़ा जा रहा है...',
    processingMsg2: 'आपकी दवाइयों को समझा जा रहा है...',
    processingMsg3: 'सब कुछ आपके लिए तैयार किया जा रहा है...',
    processingWait: 'कृपया प्रतीक्षा करें। इसमें एक मिनट लग सकता है।',
    listenButton: '🔊 सुनें',
    readButton: '📖 पढ़ें',
    pauseButton: '⏸ रोकें',
    stopButton: '⏹ बंद करें',
    resumeButton: '▶️ फिर से शुरू करें',
    askPlaceholder: 'अपनी दवाइयों के बारे में कुछ भी पूछें...',
    sendButton: 'भेजें →',
    addReminders: '📅 दवाई की याद दिलाएं जोड़ें',
    newDocument: '📤 नया दस्तावेज़',
    greetingPrefix: '🤝 नमस्ते! मैंने आपका दस्तावेज़ पढ़ लिया है। आपके डॉक्टर ने यह कहा है 👇',
    generatingAudio: '🎵 ऑडियो बनाया जा रहा है... (पहली बार थोड़ा समय लग सकता है)',
    audioGenerationComplete: '✅ ऑडियो तैयार हो गया',
    playAudioButton: '▶️ ऑडियो चलाएं',
    replayAudioButton: '🔄 शुरू से फिर चलाएं',
    downloadAudioButton: '💾 इसे मेरे सिस्टम में सेव करें',
    audioDownloaded: '✅ डाउनलोड हो गया',
  },
  kannada: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'ನಿಮ್ಮ ಔಷಧಗಳನ್ನು ಸರಳವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    dropzone: 'ನಿಮ್ಮ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಇಲ್ಲಿ ಹಾಕಿ\nಅಥವಾ ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    dropzoneHint: 'ಸ್ವೀಕೃತ: PDF, JPG, PNG  •  ಗರಿಷ್ಠ ಗಾತ್ರ: 20MB',
    processButton: '📤  ನನ್ನ ದಾಖಲೆ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ',
    connectCalendar: '📅 Google Calendar ಸಂಪರ್ಕಿಸಿ (ಐಚ್ಛಿಕ)',
    calendarConnected: '✅ Google Calendar ಸಂಪರ್ಕಗೊಂಡಿದೆ',
    processingMsg1: 'ನಿಮ್ಮ ದಾಖಲೆ ಓದಲಾಗುತ್ತಿದೆ...',
    processingMsg2: 'ನಿಮ್ಮ ಔಷಧಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ...',
    processingMsg3: 'ಎಲ್ಲವನ್ನೂ ನಿಮಗಾಗಿ ತಯಾರು ಮಾಡಲಾಗುತ್ತಿದೆ...',
    processingWait: 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ. ಇದಕ್ಕೆ ಒಂದು ನಿಮಿಷ ತಗಲಬಹುದು.',
    listenButton: '🔊 ಕೇಳಿ',
    readButton: '📖 ಓದಿ',
    pauseButton: '⏸ ನಿಲ್ಲಿಸಿ',
    stopButton: '⏹ ನಿಲ್ಲಿಸಿ',
    resumeButton: '▶️ ಮುಂದುವರಿಸಿ',
    askPlaceholder: 'ನಿಮ್ಮ ಔಷಧಗಳ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ...',
    sendButton: 'ಕಳುಹಿಸಿ →',
    addReminders: '📅 ಔಷಧ ನೆನಪಿನ ಎಚ್ಚರಿಕೆ ಸೇರಿಸಿ',
    newDocument: '📤 ಹೊಸ ದಾಖಲೆ',
    greetingPrefix: '🤝 ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ದಾಖಲೆ ಓದಿದ್ದೇನೆ. ನಿಮ್ಮ ಡಾಕ್ಟರ್ ಹೇಳಿದ್ದು ಇಲ್ಲಿದೆ 👇',
    generatingAudio: '🎵 ಆಡಿಯೋ ತಯಾರಿಸಲಾಗುತ್ತಿದೆ... (ಮೊದಲ ಬಾರಿ ಸ್ವಲ್ಪ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಬಹುದು)',
    audioGenerationComplete: '✅ ಆಡಿಯೋ ತಯಾರಾಗಿದೆ',
    playAudioButton: '▶️ ಆಡಿಯೋ ಪ್ಲೇ ಮಾಡಿ',
    replayAudioButton: '🔄 ಮೊದಲಿನಿಂದ ಮತ್ತೆ ಪ್ಲೇ ಮಾಡಿ',
    downloadAudioButton: '💾 ಇದನ್ನು ನನ್ನ ಸಿಸ್ಟಂನಲ್ಲಿ ಉಳಿಸಿ',
    audioDownloaded: '✅ ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ',
  },
  bengali: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'আপনার ওষুধগুলি সহজভাবে বুঝুন।',
    dropzone: 'এখানে আপনার প্রেসক্রিপশন রাখুন\nবা ফাইল নির্বাচন করতে ক্লিক করুন',
    dropzoneHint: 'গৃহীত: PDF, JPG, PNG  •  সর্বোচ্চ আকার: 20MB',
    processButton: '📤  আমার নথি প্রক্রিয়া করুন',
    connectCalendar: '📅 Google Calendar সংযুক্ত করুন (ঐচ্ছিক)',
    calendarConnected: '✅ Google Calendar সংযুক্ত',
    processingMsg1: 'আপনার নথি পড়া হচ্ছে...',
    processingMsg2: 'আপনার ওষুধগুলি বোঝা হচ্ছে...',
    processingMsg3: 'সবকিছু আপনার জন্য প্রস্তুত করা হচ্ছে...',
    processingWait: 'অনুগ্রহ করে অপেক্ষা করুন। এতে এক মিনিট সময় লাগতে পারে।',
    listenButton: '🔊 শুনুন',
    readButton: '📖 পড়ুন',
    pauseButton: '⏸ বিরতি',
    stopButton: '⏹ বন্ধ করুন',
    resumeButton: '▶️ পুনরায় শুরু করুন',
    askPlaceholder: 'আপনার ওষুধ সম্পর্কে কিছু জিজ্ঞাসা করুন...',
    sendButton: 'পাঠান →',
    addReminders: '📅 ওষুধের অনুস্মারক যোগ করুন',
    newDocument: '📤 নতুন নথি',
    greetingPrefix: '🤝 হ্যালো! আমি আপনার নথি পড়েছি। আপনার ডাক্তার এটি বলেছেন 👇',
    generatingAudio: '🎵 অডিও তৈরি করা হচ্ছে... (প্রথমবার কিছুটা সময় নিতে পারে)',
    audioGenerationComplete: '✅ অডিও তৈরি সম্পূর্ণ',
    playAudioButton: '▶️ অডিও চালান',
    replayAudioButton: '🔄 শুরু থেকে আবার চালান',
    downloadAudioButton: '💾 আমার সিস্টেমে সংরক্ষণ করুন',
    audioDownloaded: '✅ ডাউনলোড হয়েছে',
  },
  marathi: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'तुमची औषधे सोप्या पद्धतीने समजून घ्या.',
    dropzone: 'तुमचे प्रिस्क्रिप्शन येथे टाका\nकिंवा फाइल निवडण्यासाठी क्लिक करा',
    dropzoneHint: 'स्वीकृत: PDF, JPG, PNG  •  कमाल आकार: 20MB',
    processButton: '📤  माझे दस्तऐवज प्रक्रिया करा',
    connectCalendar: '📅 Google Calendar जोडा (पर्यायी)',
    calendarConnected: '✅ Google Calendar जोडलेले आहे',
    processingMsg1: 'तुमचे दस्तऐवज वाचले जात आहे...',
    processingMsg2: 'तुमची औषधे समजून घेतली जात आहेत...',
    processingMsg3: 'सर्व काही तुमच्यासाठी तयार केले जात आहे...',
    processingWait: 'कृपया प्रतीक्षा करा. यास एक मिनिट लागू शकते.',
    listenButton: '🔊 ऐका',
    readButton: '📖 वाचा',
    pauseButton: '⏸ थांबवा',
    stopButton: '⏹ बंद करा',
    resumeButton: '▶️ पुन्हा सुरू करा',
    askPlaceholder: 'तुमच्या औषधांबद्दल काहीही विचारा...',
    sendButton: 'पाठवा →',
    addReminders: '📅 औषध स्मरणपत्र जोडा',
    newDocument: '📤 नवीन दस्तऐवज',
    greetingPrefix: '🤝 नमस्कार! मी तुमचे दस्तऐवज वाचले आहे. तुमच्या डॉक्टरांनी हे सांगितले आहे 👇',
    generatingAudio: '🎵 ऑडिओ तयार केला जात आहे... (पहिल्यांदा थोडा वेळ लागू शकतो)',
    audioGenerationComplete: '✅ ऑडिओ तयार झाला',
    playAudioButton: '▶️ ऑडिओ चालवा',
    replayAudioButton: '🔄 सुरुवातीपासून पुन्हा चालवा',
    downloadAudioButton: '💾 माझ्या सिस्टममध्ये जतन करा',
    audioDownloaded: '✅ डाउनलोड झाले',
  },
  telugu: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'మీ మందులను సులభంగా అర్థం చేసుకోండి.',
    dropzone: 'మీ ప్రిస్క్రిప్షన్‌ను ఇక్కడ వదలండి\nలేదా ఫైల్ ఎంచుకోవడానికి క్లిక్ చేయండి',
    dropzoneHint: 'అంగీకరించబడినవి: PDF, JPG, PNG  •  గరిష్ట పరిమాణం: 20MB',
    processButton: '📤  నా పత్రాన్ని ప్రాసెస్ చేయండి',
    connectCalendar: '📅 Google Calendar కనెక్ట్ చేయండి (ఐచ్ఛికం)',
    calendarConnected: '✅ Google Calendar కనెక్ట్ చేయబడింది',
    processingMsg1: 'మీ పత్రం చదవబడుతోంది...',
    processingMsg2: 'మీ మందులు అర్థం చేసుకోబడుతున్నాయి...',
    processingMsg3: 'అన్నీ మీ కోసం సిద్ధం చేయబడుతున్నాయి...',
    processingWait: 'దయచేసి వేచి ఉండండి. దీనికి ఒక నిమిషం పట్టవచ్చు.',
    listenButton: '🔊 వినండి',
    readButton: '📖 చదవండి',
    pauseButton: '⏸ పాజ్ చేయండి',
    stopButton: '⏹ ఆపండి',
    resumeButton: '▶️ మళ్లీ ప్రారంభించండి',
    askPlaceholder: 'మీ మందుల గురించి ఏదైనా అడగండి...',
    sendButton: 'పంపండి →',
    addReminders: '📅 మందుల రిమైండర్లు జోడించండి',
    newDocument: '📤 కొత్త పత్రం',
    greetingPrefix: '🤝 హలో! నేను మీ పత్రం చదివాను. మీ డాక్టర్ ఇలా చెప్పారు 👇',
    generatingAudio: '🎵 ఆడియో రూపొందించబడుతోంది... (మొదటిసారి కొంత సమయం పట్టవచ్చు)',
    audioGenerationComplete: '✅ ఆడియో రూపొందింపు పూర్తయింది',
    playAudioButton: '▶️ ఆడియో ప్లే చేయండి',
    replayAudioButton: '🔄 మొదటి నుండి మళ్లీ ప్లే చేయండి',
    downloadAudioButton: '💾 నా సిస్టమ్‌లో సేవ్ చేయండి',
    audioDownloaded: '✅ డౌన్‌లోడ్ అయింది',
  },
  assamese: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'আপোনাৰ ঔষধবোৰ সহজভাৱে বুজি লওক।',
    dropzone: 'আপোনাৰ প্ৰেছক্ৰিপশ্যন ইয়াত ৰাখক\nবা ফাইল বাছনি কৰিবলৈ ক্লিক কৰক',
    dropzoneHint: 'গ্ৰহণযোগ্য: PDF, JPG, PNG  •  সৰ্বোচ্চ আকাৰ: 20MB',
    processButton: '📤  মোৰ নথি প্ৰক্ৰিয়া কৰক',
    connectCalendar: '📅 Google Calendar সংযোগ কৰক (ঐচ্ছিক)',
    calendarConnected: '✅ Google Calendar সংযুক্ত',
    processingMsg1: 'আপোনাৰ নথি পঢ়া হৈছে...',
    processingMsg2: 'আপোনাৰ ঔষধবোৰ বুজা হৈছে...',
    processingMsg3: 'সকলো আপোনাৰ বাবে প্ৰস্তুত কৰা হৈছে...',
    processingWait: 'অনুগ্ৰহ কৰি অপেক্ষা কৰক। ইয়াত এক মিনিট সময় লাগিব পাৰে।',
    listenButton: '🔊 শুনক',
    readButton: '📖 পঢ়ক',
    pauseButton: '⏸ বিৰতি',
    stopButton: '⏹ বন্ধ কৰক',
    resumeButton: '▶️ পুনৰ আৰম্ভ কৰক',
    askPlaceholder: 'আপোনাৰ ঔষধৰ বিষয়ে কিবা সুধিব...',
    sendButton: 'পঠিয়াওক →',
    addReminders: '📅 ঔষধৰ সোঁৱৰণী যোগ কৰক',
    newDocument: '📤 নতুন নথি',
    greetingPrefix: '🤝 নমস্কাৰ! মই আপোনাৰ নথি পঢ়িছো। আপোনাৰ চিকিৎসকে এইটো কৈছে 👇',
    generatingAudio: '🎵 অডিঅ\' সৃষ্টি কৰা হৈছে... (প্ৰথমবাৰ কিছু সময় ল\'ব পাৰে)',
    audioGenerationComplete: '✅ অডিঅ\' সম্পূৰ্ণ হৈছে',
    playAudioButton: '▶️ অডিঅ\' চলাওক',
    replayAudioButton: '🔄 আৰম্ভণিৰ পৰা পুনৰ চলাওক',
    downloadAudioButton: '💾 ইয়াক মোৰ চিস্টেমত সংৰক্ষণ কৰক',
    audioDownloaded: '✅ ডাউনলোড সম্পূৰ্ণ',
  },
  gujarati: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'તમારી દવાઓને સરળતાથી સમજો.',
    dropzone: 'તમારું પ્રિસ્ક્રિપ્શન અહીં મૂકો\nઅથવા ફાઇલ પસંદ કરવા માટે ક્લિક કરો',
    dropzoneHint: 'સ્વીકૃત: PDF, JPG, PNG  •  મહત્તમ કદ: 20MB',
    processButton: '📤  મારા દસ્તાવેજની પ્રક્રિયા કરો',
    connectCalendar: '📅 Google Calendar કનેક્ટ કરો (વૈકલ્પિક)',
    calendarConnected: '✅ Google Calendar કનેક્ટ થયેલ છે',
    processingMsg1: 'તમારો દસ્તાવેજ વાંચવામાં આવી રહ્યો છે...',
    processingMsg2: 'તમારી દવાઓ સમજવામાં આવી રહી છે...',
    processingMsg3: 'બધું તમારા માટે તૈયાર કરવામાં આવી રહ્યું છે...',
    processingWait: 'કૃપા કરીને રાહ જુઓ. આમાં એક મિનિટ લાગી શકે છે.',
    listenButton: '🔊 સાંભળો',
    readButton: '📖 વાંચો',
    pauseButton: '⏸ થોભાવો',
    stopButton: '⏹ બંધ કરો',
    resumeButton: '▶️ ફરી શરૂ કરો',
    askPlaceholder: 'તમારી દવાઓ વિશે કંઈપણ પૂછો...',
    sendButton: 'મોકલો →',
    addReminders: '📅 દવાના રિમાઇન્ડર ઉમેરો',
    newDocument: '📤 નવો દસ્તાવેજ',
    greetingPrefix: '🤝 નમસ્તે! મેં તમારો દસ્તાવેજ વાંચ્યો છે. તમારા ડૉક્ટરે આ કહ્યું છે 👇',
    generatingAudio: '🎵 ઑડિયો બનાવવામાં આવી રહ્યો છે... (પ્રથમ વખત થોડો સમય લાગી શકે છે)',
    audioGenerationComplete: '✅ ઑડિયો તૈયાર થઈ ગયો',
    playAudioButton: '▶️ ઑડિયો ચલાવો',
    replayAudioButton: '🔄 શરૂઆતથી ફરી ચલાવો',
    downloadAudioButton: '💾 તેને મારા સિસ્ટમમાં સેવ કરો',
    audioDownloaded: '✅ ડાઉનલોડ થયું',
  },
  malayalam: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'നിങ്ങളുടെ മരുന്നുകൾ ലളിതമായി മനസ്സിലാക്കുക.',
    dropzone: 'നിങ്ങളുടെ കുറിപ്പടി ഇവിടെ ഇടുക\nഅല്ലെങ്കിൽ ഫയൽ തിരഞ്ഞെടുക്കാൻ ക്ലിക്ക് ചെയ്യുക',
    dropzoneHint: 'സ്വീകരിച്ചത്: PDF, JPG, PNG  •  പരമാവധി വലുപ്പം: 20MB',
    processButton: '📤  എന്റെ രേഖ പ്രോസസ്സ് ചെയ്യുക',
    connectCalendar: '📅 Google Calendar കണക്റ്റ് ചെയ്യുക (ഓപ്ഷണൽ)',
    calendarConnected: '✅ Google Calendar കണക്റ്റ് ചെയ്തു',
    processingMsg1: 'നിങ്ങളുടെ രേഖ വായിക്കുന്നു...',
    processingMsg2: 'നിങ്ങളുടെ മരുന്നുകൾ മനസ്സിലാക്കുന്നു...',
    processingMsg3: 'എല്ലാം നിങ്ങൾക്കായി തയ്യാറാക്കുന്നു...',
    processingWait: 'ദയവായി കാത്തിരിക്കുക. ഇതിന് ഒരു മിനിറ്റ് എടുത്തേക്കാം.',
    listenButton: '🔊 കേൾക്കുക',
    readButton: '📖 വായിക്കുക',
    pauseButton: '⏸ താൽക്കാലികമായി നിർത്തുക',
    stopButton: '⏹ നിർത്തുക',
    resumeButton: '▶️ വീണ്ടും ആരംഭിക്കുക',
    askPlaceholder: 'നിങ്ങളുടെ മരുന്നുകളെക്കുറിച്ച് എന്തും ചോദിക്കുക...',
    sendButton: 'അയയ്ക്കുക →',
    addReminders: '📅 മരുന്ന് ഓർമ്മപ്പെടുത്തലുകൾ ചേർക്കുക',
    newDocument: '📤 പുതിയ രേഖ',
    greetingPrefix: '🤝 ഹലോ! ഞാൻ നിങ്ങളുടെ രേഖ വായിച്ചു. നിങ്ങളുടെ ഡോക്ടർ ഇത് പറഞ്ഞു 👇',
    generatingAudio: '🎵 ഓഡിയോ സൃഷ്ടിക്കുന്നു... (ആദ്യം കുറച്ച് സമയമെടുത്തേക്കാം)',
    audioGenerationComplete: '✅ ഓഡിയോ തയ്യാറായി',
    playAudioButton: '▶️ ഓഡിയോ പ്ലേ ചെയ്യുക',
    replayAudioButton: '🔄 ആരംഭത്തിൽ നിന്ന് വീണ്ടും പ്ലേ ചെയ്യുക',
    downloadAudioButton: '💾 ഇത് എന്റെ സിസ്റ്റത്തിൽ സേവ് ചെയ്യുക',
    audioDownloaded: '✅ ഡൗൺലോഡ് ചെയ്തു',
  },
  punjabi: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'ਆਪਣੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ਸੌਖੇ ਤਰੀਕੇ ਨਾਲ ਸਮਝੋ।',
    dropzone: 'ਆਪਣਾ ਨੁਸਖਾ ਇੱਥੇ ਰੱਖੋ\nਜਾਂ ਫਾਈਲ ਚੁਣਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    dropzoneHint: 'ਸਵੀਕਾਰ ਕੀਤਾ: PDF, JPG, PNG  •  ਵੱਧ ਤੋਂ ਵੱਧ ਆਕਾਰ: 20MB',
    processButton: '📤  ਮੇਰੇ ਦਸਤਾਵੇਜ਼ ਦੀ ਪ੍ਰਕਿਰਿਆ ਕਰੋ',
    connectCalendar: '📅 Google Calendar ਕਨੈਕਟ ਕਰੋ (ਵਿਕਲਪਿਕ)',
    calendarConnected: '✅ Google Calendar ਕਨੈਕਟ ਹੋਇਆ',
    processingMsg1: 'ਤੁਹਾਡਾ ਦਸਤਾਵੇਜ਼ ਪੜ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    processingMsg2: 'ਤੁਹਾਡੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ਸਮਝਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    processingMsg3: 'ਸਭ ਕੁਝ ਤੁਹਾਡੇ ਲਈ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    processingWait: 'ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ। ਇਸ ਵਿੱਚ ਇੱਕ ਮਿੰਟ ਲੱਗ ਸਕਦਾ ਹੈ।',
    listenButton: '🔊 ਸੁਣੋ',
    readButton: '📖 ਪੜ੍ਹੋ',
    pauseButton: '⏸ ਰੋਕੋ',
    stopButton: '⏹ ਬੰਦ ਕਰੋ',
    resumeButton: '▶️ ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    askPlaceholder: 'ਆਪਣੀਆਂ ਦਵਾਈਆਂ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ...',
    sendButton: 'ਭੇਜੋ →',
    addReminders: '📅 ਦਵਾਈ ਯਾਦ ਦਿਵਾਉਣ ਵਾਲੇ ਸ਼ਾਮਲ ਕਰੋ',
    newDocument: '📤 ਨਵਾਂ ਦਸਤਾਵੇਜ਼',
    greetingPrefix: '🤝 ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡਾ ਦਸਤਾਵੇਜ਼ ਪੜ੍ਹ ਲਿਆ ਹੈ। ਤੁਹਾਡੇ ਡਾਕਟਰ ਨੇ ਇਹ ਕਿਹਾ ਹੈ 👇',
    generatingAudio: '🎵 ਆਡੀਓ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ... (ਪਹਿਲੀ ਵਾਰ ਥੋੜ੍ਹਾ ਸਮਾਂ ਲੱਗ ਸਕਦਾ ਹੈ)',
    audioGenerationComplete: '✅ ਆਡੀਓ ਤਿਆਰ ਹੋ ਗਿਆ',
    playAudioButton: '▶️ ਆਡੀਓ ਚਲਾਓ',
    replayAudioButton: '🔄 ਸ਼ੁਰੂ ਤੋਂ ਮੁੜ ਚਲਾਓ',
    downloadAudioButton: '💾 ਇਸਨੂੰ ਮੇਰੇ ਸਿਸਟਮ ਵਿੱਚ ਸੰਭਾਲੋ',
    audioDownloaded: '✅ ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ',
  },
  tamil: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'உங்கள் மருந்துகளை எளிதாகப் புரிந்து கொள்ளுங்கள்.',
    dropzone: 'உங்கள் மருந்துச் சீட்டை இங்கே வைக்கவும்\nஅல்லது கோப்பைத் தேர்ந்தெடுக்க கிளிக் செய்யவும்',
    dropzoneHint: 'ஏற்றுக்கொள்ளப்பட்டது: PDF, JPG, PNG  •  அதிகபட்ச அளவு: 20MB',
    processButton: '📤  எனது ஆவணத்தைச் செயலாக்கவும்',
    connectCalendar: '📅 Google Calendar இணைக்கவும் (விருப்பத்தேர்வு)',
    calendarConnected: '✅ Google Calendar இணைக்கப்பட்டது',
    processingMsg1: 'உங்கள் ஆவணம் படிக்கப்படுகிறது...',
    processingMsg2: 'உங்கள் மருந்துகள் புரிந்து கொள்ளப்படுகின்றன...',
    processingMsg3: 'அனைத்தும் உங்களுக்காக தயாராகிறது...',
    processingWait: 'தயவுசெய்து காத்திருக்கவும். இதற்கு ஒரு நிமிடம் ஆகலாம்.',
    listenButton: '🔊 கேளுங்கள்',
    readButton: '📖 படியுங்கள்',
    pauseButton: '⏸ இடைநிறுத்தவும்',
    stopButton: '⏹ நிறுத்தவும்',
    resumeButton: '▶️ மீண்டும் தொடங்கவும்',
    askPlaceholder: 'உங்கள் மருந்துகள் பற்றி எதையும் கேளுங்கள்...',
    sendButton: 'அனுப்பவும் →',
    addReminders: '📅 மருந்து நினைவூட்டல்களைச் சேர்க்கவும்',
    newDocument: '📤 புதிய ஆவணம்',
    greetingPrefix: '🤝 வணக்கம்! நான் உங்கள் ஆவணத்தைப் படித்தேன். உங்கள் மருத்துவர் இதைச் சொன்னார் 👇',
    generatingAudio: '🎵 ஆடியோ உருவாக்கப்படுகிறது... (முதல் முறை சிறிது நேரம் ஆகலாம்)',
    audioGenerationComplete: '✅ ஆடியோ தயாராகிவிட்டது',
    playAudioButton: '▶️ ஆடியோ இயக்கவும்',
    replayAudioButton: '🔄 தொடக்கம் முதல் மீண்டும் இயக்கவும்',
    downloadAudioButton: '💾 இதை என் கணினியில் சேமிக்கவும்',
    audioDownloaded: '✅ பதிவிறக்கம் முடிந்தது',
  },
  nepali: {
    uploadTitle: '💊 MedEase',
    uploadSubtitle: 'तपाईंका औषधिहरू सजिलै बुझ्नुहोस्।',
    dropzone: 'तपाईंको प्रिस्क्रिप्शन यहाँ राख्नुहोस्\nवा फाइल छान्न क्लिक गर्नुहोस्',
    dropzoneHint: 'स्वीकृत: PDF, JPG, PNG  •  अधिकतम आकार: 20MB',
    processButton: '📤  मेरो कागजात प्रशोधन गर्नुहोस्',
    connectCalendar: '📅 Google Calendar जडान गर्नुहोस् (वैकल्पिक)',
    calendarConnected: '✅ Google Calendar जडान भयो',
    processingMsg1: 'तपाईंको कागजात पढिँदैछ...',
    processingMsg2: 'तपाईंका औषधिहरू बुझिँदैछ...',
    processingMsg3: 'सबै तपाईंको लागि तयार गरिँदैछ...',
    processingWait: 'कृपया पर्खनुहोस्। यसमा एक मिनेट लाग्न सक्छ।',
    listenButton: '🔊 सुन्नुहोस्',
    readButton: '📖 पढ्नुहोस्',
    pauseButton: '⏸ रोक्नुहोस्',
    stopButton: '⏹ बन्द गर्नुहोस्',
    resumeButton: '▶️ फेरि सुरु गर्नुहोस्',
    askPlaceholder: 'तपाईंका औषधिहरूको बारेमा केही पनि सोध्नुहोस्...',
    sendButton: 'पठाउनुहोस् →',
    addReminders: '📅 औषधि सम्झना थप्नुहोस्',
    newDocument: '📤 नयाँ कागजात',
    greetingPrefix: '🤝 नमस्ते! मैले तपाईंको कागजात पढें। तपाईंको डाक्टरले यो भन्नुभयो 👇',
    generatingAudio: '🎵 अडियो उत्पन्न गरिँदैछ... (पहिलो पटक केही समय लाग्न सक्छ)',
    audioGenerationComplete: '✅ अडियो तयार भयो',
    playAudioButton: '▶️ अडियो प्ले गर्नुहोस्',
    replayAudioButton: '🔄 सुरुबाट फेरि प्ले गर्नुहोस्',
    downloadAudioButton: '💾 यसलाई मेरो सिस्टममा सेभ गर्नुहोस्',
    audioDownloaded: '✅ डाउनलोड भयो',
  },
};

export function getLabels(language: Language): UILabels {
  return LABELS[language];
}